name: GitHub Workflow Demo on GKE
on: [push] # pull_request is also possible, and for forked PRs will require approval from a repo maintainer to run

jobs:
  GKE-Runner-Demo:
    runs-on: self-hosted # this line makes it run on GKE
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 🐧 This job is now running on a GKE instance
        run: |
          echo instance name: $(curl 'http://metadata.google.internal/computeMetadata/v1/instance/name' -sH 'Metadata-Flavor: Google')
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: whoami
      - run: docker run --rm hello-world
      - run: echo "🍏 This job's status is ${{ job.status }}."
